package distritoswebservices.model.POJOS;
// Generated 19/02/2018 by Hibernate Tools 4.3.1



/**
 * Distritos generated by hbm2java
 */
public class Distritos  implements java.io.Serializable {


     private Integer id;
     private Estados estados;
     private int idDistrito;
     private String distrito;
     private int casillas;

    public Distritos() {
    }

    public Distritos(Estados estados, int idDistrito, String distrito, int casillas) {
       this.estados = estados;
       this.idDistrito = idDistrito;
       this.distrito = distrito;
       this.casillas = casillas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estados getEstados() {
        return this.estados;
    }
    
    public void setEstados(Estados estados) {
        this.estados = estados;
    }
    public int getIdDistrito() {
        return this.idDistrito;
    }
    
    public void setIdDistrito(int idDistrito) {
        this.idDistrito = idDistrito;
    }
    public String getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(String distrito) {
        this.distrito = distrito;
    }
    public int getCasillas() {
        return this.casillas;
    }
    
    public void setCasillas(int casillas) {
        this.casillas = casillas;
    }
}


